
plugin "cocoapods-frost"

use_frameworks!
platform :ios, '12.0'

install! "cocoapods",
         :generate_multiple_pod_projects => true,
         :incremental_installation => false


target 'Demo' do

  frost_pod "Moya"

# frost_pod "Texture/Core", path: "./Pods/Frost/out"
#  pod "Texture/Video", path: "./Pods/Frost/out"

  frost_pod "JAYSON"
  
  # pod "Brightroom"

  pod "FBSDKCoreKit"
  pod "FBSDKLoginKit"

  frost_pod "SSZipArchive"
  
  frost_pod "SwiftDate"
  frost_pod "RxSwift"
  frost_pod "RxCocoa"
  frost_pod "RxRelay"
  frost_pod "RxFuture"
  frost_pod "lottie-ios"

  # pod "Verge"
  # pod "Firebase/Core"
  # pod "Firebase/Performance"
  # pod "Firebase/Messaging"
  # pod "Firebase/InAppMessaging"
  # pod "Firebase/Auth"
  # pod "FirebaseUI/Phone"
  # pod "FirebaseUI/OAuth"
  # pod "Firebase/Crashlytics"
  # pod "Firebase/Analytics"

  # pod "gRPC-Swift", ">=1.4.2"
  
  frost_pod "MagazineLayout"
  frost_pod "SVGKit"
end

pre_install do |installer|
  # p "hoge"
  # installer.generated_projects.each do |project|
  #   puts "hhh"
  #   project.targets.each do |target|
  #     config.build_settings['SWIFT_VERSION'] = '5.5'
  #   end
  # end
end
